# Setup
title:        Filter Drawer
tagline:      Android plug-and-play filter that slides
baseurl:      "/FilterDrawer"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Camerash
  url:        https://github.com/Camerash 

#Others
markdown: kramdown
theme: jekyll-theme-cayman